general:
  use_uvloop: true
  telemetry:
    logging:
      console:
        _type: console
        level: CRITICAL
functions:
  web_search_tool:
    _type: serp_api_tool
    api_key: ${SERP_API_KEY}
llms:
  openai:
    _type: openai
    model_name: gpt-4.1
    temperature: 0
workflow:
  _type: xpander_nemo_agent
  llm_name: openai
  tools: [web_search_tool]
  verbose: false
  retry_parsing_errors: true
  max_retries: 3
